### ISSUE TITLE
Assertion failures in depthComp.cpp

### ISSUE THREAD

**Issue by pathi** [atapour/depthComp#6]
I created a visual studio project using the given header file and its .cpp file, and when I try to run the main file using images in the Example folder, Visual studio gave multiple run time errors saying:

"_Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at_"
in the for loop of "_preProcess_"

and

" _Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at_"
in the for loop of "identFillHoles".

Any insight would be highly appreciated...

**Comment by atapour** [comment]
I have just tested the code on my own machine and it works.

Unfortunately, I am not familiar with Visual Studio and cannot help you with the environment, but if I were to guess, I would say the input images are not passed into the code (as arguments) properly, and empty Mat objects are being processed, resulting in errors.

**Comment by pathi** [comment]
Thank you for responding. 
However, the assertion failure caused not because the images were not passed into the methods. I add a few boundary constraints in the for loops and managed to run the program. 
Thank you.
