### ISSUE TITLE
how to get the correct 16-bit output depth map

### ISSUE THREAD

**Issue by 2585157341** [atapour/depthComp#7]
Hello, your algorithm is very interesting, but I have a question, your output depth map is 8 bits png, not the  16-bit depth map, I noticed that the image pixels in the code are normalized to 0-255, so how to get the correct 16-bit depth map that has been completed

**Comment by atapour** [comment]
Thank you very much for your interest. While the depth map is normalised for ease of processing in the demonstration code here, the principles of the algorithm work the same regardless of the bit depth or the range of values in the image. By changing the normalisation, you can apply the same method to 16-bit images as well.
